name: w
description: "A Flutter package that adds a fun dab animation to your widgets."
version: 1.1.0
repository: https://github.com/wdestroier/w

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  material_ui: ^1.0.0
